SET DEFINE OFF;

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE USERS (
       ID VARCHAR2(50) PRIMARY KEY,
       NAME VARCHAR2(100) NOT NULL,
       EMAIL VARCHAR2(100) UNIQUE NOT NULL,
       PASSWORD VARCHAR2(100) NOT NULL,
       ROLE VARCHAR2(20) CHECK (ROLE IN (''admin'', ''teacher'', ''cr'')) NOT NULL,
       DEPARTMENT_ID VARCHAR2(50),
       BATCH_ID VARCHAR2(50),
       SECTION_ID VARCHAR2(50)
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE DEPARTMENTS (
       ID VARCHAR2(50) PRIMARY KEY,
       NAME VARCHAR2(100) UNIQUE NOT NULL
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE BATCHES (
       ID VARCHAR2(50) PRIMARY KEY,
       DEPARTMENT_ID VARCHAR2(50) NOT NULL,
       NAME VARCHAR2(100) NOT NULL,
       CONSTRAINT FK_BATCH_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE CASCADE
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE SECTIONS (
       ID VARCHAR2(50) PRIMARY KEY,
       BATCH_ID VARCHAR2(50) NOT NULL,
       NAME VARCHAR2(100) NOT NULL,
       CONSTRAINT FK_SEC_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID) ON DELETE CASCADE
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE ACTIVITIES (
       ID VARCHAR2(50) PRIMARY KEY,
       DEPARTMENT_ID VARCHAR2(50) NOT NULL,
       BATCH_ID VARCHAR2(50) NOT NULL,
       SECTION_ID VARCHAR2(50) NOT NULL,
       ACTIVITY_TYPE VARCHAR2(30) NOT NULL,
       TITLE VARCHAR2(200) NOT NULL,
       SUBJECT VARCHAR2(100) NOT NULL,
       ROOM VARCHAR2(50),
       DESCRIPTION VARCHAR2(500),
       EVENT_DATE VARCHAR2(30),
       START_DATE VARCHAR2(30),
       END_DATE VARCHAR2(30),
       CREATED_BY VARCHAR2(50) NOT NULL,
       CONSTRAINT FK_ACT_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE CASCADE,
       CONSTRAINT FK_ACT_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID) ON DELETE CASCADE,
       CONSTRAINT FK_ACT_SEC FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS(ID) ON DELETE CASCADE,
       CONSTRAINT FK_ACT_USER FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE ACTIVITY_LOGS (
       LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       ACTIVITY_ID VARCHAR2(50),
       ACTION_TYPE VARCHAR2(10),
       PERFORMED_BY VARCHAR2(50),
       LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   )';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_VALIDATE_USER_DATA
BEFORE INSERT OR UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.EMAIL := LOWER(TRIM(:NEW.EMAIL));

    IF :NEW.ROLE = 'cr' THEN
        IF :NEW.DEPARTMENT_ID IS NULL OR :NEW.BATCH_ID IS NULL OR :NEW.SECTION_ID IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'CR user must have department, batch, and section.');
        END IF;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_CHECK_CR_ACTIVITY_SCOPE
BEFORE INSERT OR UPDATE ON ACTIVITIES
FOR EACH ROW
DECLARE
    v_role USERS.ROLE%TYPE;
    v_dept USERS.DEPARTMENT_ID%TYPE;
    v_batch USERS.BATCH_ID%TYPE;
    v_sec USERS.SECTION_ID%TYPE;
BEGIN
    SELECT ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID
    INTO v_role, v_dept, v_batch, v_sec
    FROM USERS
    WHERE ID = :NEW.CREATED_BY;

    IF v_role = 'cr' THEN
        IF :NEW.DEPARTMENT_ID != v_dept OR :NEW.BATCH_ID != v_batch OR :NEW.SECTION_ID != v_sec THEN
            RAISE_APPLICATION_ERROR(-20002, 'CR can only create activities in assigned section.');
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'Creator user not found.');
END;
/
CREATE OR REPLACE TRIGGER TRG_AUDIT_ACTIVITIES
AFTER INSERT OR UPDATE OR DELETE ON ACTIVITIES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO ACTIVITY_LOGS (ACTIVITY_ID, ACTION_TYPE, PERFORMED_BY)
        VALUES (:NEW.ID, 'INSERT', :NEW.CREATED_BY);
    ELSIF UPDATING THEN
        INSERT INTO ACTIVITY_LOGS (ACTIVITY_ID, ACTION_TYPE, PERFORMED_BY)
        VALUES (:NEW.ID, 'UPDATE', :NEW.CREATED_BY);
    ELSIF DELETING THEN
        INSERT INTO ACTIVITY_LOGS (ACTIVITY_ID, ACTION_TYPE, PERFORMED_BY)
        VALUES (:OLD.ID, 'DELETE', :OLD.CREATED_BY);
    END IF;
END;
/
DECLARE
   v_user_count NUMBER := 0;
BEGIN
   SELECT COUNT(*) INTO v_user_count FROM USERS;
   IF v_user_count = 0 THEN
      BEGIN INSERT INTO DEPARTMENTS (ID, NAME) VALUES ('dept-1', 'Computer Science & Engineering'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
      BEGIN INSERT INTO DEPARTMENTS (ID, NAME) VALUES ('dept-2', 'Electrical & Electronic Engineering'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;

      BEGIN INSERT INTO BATCHES (ID, DEPARTMENT_ID, NAME) VALUES ('batch-1', 'dept-1', 'Batch 55'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
      BEGIN INSERT INTO BATCHES (ID, DEPARTMENT_ID, NAME) VALUES ('batch-2', 'dept-1', 'Batch 56'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;

      BEGIN INSERT INTO SECTIONS (ID, BATCH_ID, NAME) VALUES ('sec-1', 'batch-1', 'Section A'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
      BEGIN INSERT INTO SECTIONS (ID, BATCH_ID, NAME) VALUES ('sec-2', 'batch-1', 'Section B'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;

      BEGIN INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID) VALUES ('u-admin', 'System Admin', 'admin@unify.edu', 'admin123', 'admin', NULL, NULL, NULL); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
      BEGIN INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID) VALUES ('u-teacher', 'Dr. Alan Turing', 'teacher@unify.edu', 'teacher123', 'teacher', 'dept-1', NULL, NULL); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
      BEGIN INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID) VALUES ('u-cr', 'John Doe (CR)', 'cr@unify.edu', 'cr123', 'cr', 'dept-1', 'batch-1', 'sec-1'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;

      BEGIN INSERT INTO ACTIVITIES (ID, DEPARTMENT_ID, BATCH_ID, SECTION_ID, ACTIVITY_TYPE, TITLE, SUBJECT, ROOM, DESCRIPTION, EVENT_DATE, CREATED_BY) VALUES ('act-1', 'dept-1', 'batch-1', 'sec-1', 'class-test', 'Database Systems CT 1', 'CSE-3101', 'Room 402', 'Topics: ER Diagrams & SQL Queries', '2026-08-10', 'u-teacher'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
   END IF;
END;
/

COMMIT;
