-- Unify Oracle DB Initialization Script (SQL*Plus compatible)
SET DEFINE OFF;

-- Drop existing tables if re-initializing
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ACTIVITIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SECTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BATCHES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create Tables
CREATE TABLE USERS (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('admin', 'teacher', 'cr')) NOT NULL,
    DEPARTMENT_ID VARCHAR2(50),
    BATCH_ID VARCHAR2(50),
    SECTION_ID VARCHAR2(50)
);

CREATE TABLE DEPARTMENTS (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE BATCHES (
    ID VARCHAR2(50) PRIMARY KEY,
    DEPARTMENT_ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_BATCH_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE CASCADE
);

CREATE TABLE SECTIONS (
    ID VARCHAR2(50) PRIMARY KEY,
    BATCH_ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_SEC_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITIES (
    ID VARCHAR2(50) PRIMARY KEY,
    DEPARTMENT_ID VARCHAR2(50) NOT NULL,
    BATCH_ID VARCHAR2(50) NOT NULL,
    SECTION_ID VARCHAR2(50) NOT NULL,
    ACTIVITY_TYPE VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    SUBJECT VARCHAR2(100) NOT NULL,
    ROOM VARCHAR2(50),
    DESCRIPTION VARCHAR2(500),
    EVENT_DATE VARCHAR2(30),
    START_DATE VARCHAR2(30),
    END_DATE VARCHAR2(30),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ACT_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACT_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACT_SEC FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACT_USER FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Seed Data
INSERT INTO DEPARTMENTS (ID, NAME) VALUES ('dept-1', 'Computer Science & Engineering');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES ('dept-2', 'Electrical & Electronic Engineering');

INSERT INTO BATCHES (ID, DEPARTMENT_ID, NAME) VALUES ('batch-1', 'dept-1', 'Batch 55');
INSERT INTO BATCHES (ID, DEPARTMENT_ID, NAME) VALUES ('batch-2', 'dept-1', 'Batch 56');

INSERT INTO SECTIONS (ID, BATCH_ID, NAME) VALUES ('sec-1', 'batch-1', 'Section A');
INSERT INTO SECTIONS (ID, BATCH_ID, NAME) VALUES ('sec-2', 'batch-1', 'Section B');

-- Default Seed Users (Password is plain text for basic auth requirement)
INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID)
VALUES ('u-admin', 'System Admin', 'admin@unify.edu', 'admin123', 'admin', NULL, NULL, NULL);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID)
VALUES ('u-teacher', 'Dr. Alan Turing', 'teacher@unify.edu', 'teacher123', 'teacher', 'dept-1', NULL, NULL);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLE, DEPARTMENT_ID, BATCH_ID, SECTION_ID)
VALUES ('u-cr', 'John Doe (CR)', 'cr@unify.edu', 'cr123', 'cr', 'dept-1', 'batch-1', 'sec-1');

-- Seed Sample Activity
INSERT INTO ACTIVITIES (ID, DEPARTMENT_ID, BATCH_ID, SECTION_ID, ACTIVITY_TYPE, TITLE, SUBJECT, ROOM, DESCRIPTION, EVENT_DATE, CREATED_BY)
VALUES ('act-1', 'dept-1', 'batch-1', 'sec-1', 'class-test', 'Database Systems CT 1', 'CSE-3101', 'Room 402', 'Topics: ER Diagrams & SQL Queries', '2026-08-10', 'u-teacher');

COMMIT;
